# Generated by Django 3.2.9 on 2023-05-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=256)),
                ('cnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=256)),
                ('cep', models.CharField(max_length=9)),
                ('municipio', models.CharField(max_length=256)),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=256)),
                ('nome_contato', models.CharField(max_length=256)),
            ],
        ),
    ]
